# Dependencies
markdown:             kramdown
kramdown:
  input:              GFM
  syntax_highlighter: rouge

# Permalinks
permalink:            pretty

# Setup
title:                Entry Docs
tagline:              'Entry Docs'
description:          '엔트리 개발 가이드'
url:                  https://entrylabs.github.io
baseurl:              /docs/
imageurl:             /docs/public/image/
base-link-url:        /docs
port:                 5000

author:
  name:               'kimorkim'
  url:                https://www.playentry.org

github:
  repo:                   https://github.com/entrylabs

paginate:             5
paginate_path:        "/posts/page:num/"

# Custom vars
version:              1.0.0

# Gems
gems: [jekyll-paginate, jekyll-gist]

exclude: [vendor]