# Dependencies
timezone:             Asia/Seoul
markdown:             kramdown
kramdown:
  input:              GFM
  syntax_highlighter: rouge

# Permalinks
permalink:            pretty

# Setup
#logo: /siteicon.png
title:                'Entry Docs'
tagline:              'Entry Docs'
description:          '엔트리 개발 가이드'
url:                  https://entrylabs.github.io
baseurl:              /docs
imageurl:             /docs/images/
base-link-url:        /docs
port:                 5000

author:
  name:               'kimorkim'
  url:                https://www.playentry.org

github:
  repo:               https://github.com/entrylabs

paginate:             5
paginate_path:        "/posts/page:num/"

# Custom vars
version:              1.0.0

# Gems
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  
collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

types:
  - minor
  - major